import os
import logging
from google.adk.tools.tool_context import ToolContext
from google.api_core.client_options import ClientOptions
from google.cloud import discoveryengine_v1 as discoveryengine
from google.auth.transport.requests import Request
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

# Configuration
PROJECT = os.environ.get("GCP_PROJECT_ID")
LOCATION = "global"
ENGINE_ID = os.environ.get("ENGINE_ID") 
USER_CREDENTIAL_CACHE = {}

# =================================================================
# --- HELPER FUNCTIONS ---
# =================================================================
def update_state(key: str, value: str, tool_context: ToolContext):
    tool_context.state[key] = value
    return value

def get_state(key: str, tool_context: ToolContext) -> str:
    return tool_context.state.get(key, None)

# =================================================================
# --- SEARCH TOOL ---
# =================================================================
def call_agentspace_search_api(query: str, tool_context: ToolContext) -> str:
    print(f"\n[DEBUG] --- Tool 'call_agentspace_search_api' started ---")

    # 1. GET USER ID & CREDENTIALS
    slack_user_id = getattr(tool_context, "user_id", None) or tool_context.state.get("slack_user_id")
    if not slack_user_id:
        return "System Error: Unable to identify user context."

    user_creds = USER_CREDENTIAL_CACHE.get(slack_user_id)
    if not user_creds:
       return "System Error: Credentials not found. Please log in again."

    # 2. VERIFY IDENTITY & REFRESH
    try:
       if not user_creds.valid:
           user_creds.refresh(Request())
    except Exception as e:
       print(f"[DEBUG] Auth Refresh Failed: {e}")

    # 3. EXECUTE STREAM ASSIST
    try:
        client_options = (
            ClientOptions(api_endpoint=f"{LOCATION}-discoveryengine.googleapis.com")
            if LOCATION != "global" else None
        )

        client = discoveryengine.AssistantServiceClient(
            credentials=user_creds, 
            client_options=client_options,
            transport="rest" 
        )

        # --- SMART QUERY WRAPPER ---
        # Gently turn short keywords into a question so Vertex doesn't skip it.
        # Removes the confusing "knowledge base" phrase.
        if "?" not in query and len(query.split()) < 5:
            query_to_send = f"What can you tell me about {query}?"
        else:
            query_to_send = query
        
        request_args = {
            "name": client.assistant_path(
                project=PROJECT,
                location=LOCATION,
                collection="default_collection",
                engine=ENGINE_ID,
                assistant="default_assistant",
            ),
            "query": discoveryengine.Query(text=query_to_send),
        }

        # Multi-turn conversational memory
        existing_session_id = tool_context.state.get("vertex_search_session_id")
        if existing_session_id:
            request_args["session"] = existing_session_id

        request = discoveryengine.StreamAssistRequest(**request_args)

        print(f"[DEBUG] Sending SDK query: '{query_to_send}'")
        
        # Make the streaming request over HTTP
        stream = client.stream_assist(request=request)

        accumulated_text = ""
        new_session_id = None

        # Handle the stream chunks gracefully
        for response in stream:
            # 1. Capture session ID
            if response.session_info and response.session_info.session:
                new_session_id = response.session_info.session

            # 2. Iterate through model replies safely
            for reply in getattr(response.answer, "replies",[]):
                
                # Check if grounded_content exists
                if hasattr(reply, "grounded_content") and hasattr(reply.grounded_content, "content"):
                    content_block = reply.grounded_content.content
                    
                    # Filter out thought processes
                    if getattr(content_block, "thought", False):
                        continue
                        
                    # Capture actual text generated by the model
                    if getattr(content_block, "role", "") == "model" and getattr(content_block, "text", ""):
                        accumulated_text += content_block.text

        # Update ADK memory
        if new_session_id:
            tool_context.state["vertex_search_session_id"] = new_session_id
            print(f"[DEBUG] Saved Vertex Session ID: {new_session_id}")

        if not accumulated_text:
            return "I searched the knowledge base but couldn't generate a summary."
            
        print(f"[DEBUG] SDK successfully retrieved text length: {len(accumulated_text)}")
        
        # --- NEW VISIBILITY ---
        print(f"\n[DEBUG] VERTEX AI RETURNED:\n{accumulated_text}\n")
        
        return accumulated_text

    except Exception as e:
        print(f"[DEBUG] CRITICAL SDK ERROR: {e}")
        return f"System Error: {str(e)}"